### PR TITLE
CE-868 - Update Map Popup Layout

### PR DESCRIPTION
**Pull request by jeznorth**
# Description

Please provide a summary of the change and the issue fixed. Please include relevant context. List dependency changes.

Fixes # (issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Further comments

---

Thanks for the PR!

Any successful deployments (not always required) will be available below.
[Backend](https://nr-compliance-enforcement-512-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-512-frontend.apps.silver.devops.gov.bc.ca/) available

Once merged, code will be promoted and handed off to following workflow run.
[Main Merge Workflow](https://github.com/bcgov/nr-compliance-enforcement/actions/workflows/merge-main.yml)

### CODE REVIEW

**Comment by Scarlett-Truong** [comment]
@jeznorth I view this in Google using Mac, and it has this weird icon "?". 
Also this line has black colour, which is different from the greyish in the design 🤔
Screen Shot 2024-07-10 at 10 01 24 AM

**Comment by Scarlett-Truong** [comment]
Out of scope question: sometimes the "...complaints could not be mapped" is covering the tooltip's header, so the complaint number, status and sometimes the line below it cannot be seen, and users have to move the map around to find perfect spot to view the tooltip. Do we want to address this UIUX issue? 🤔

**Comment by jeznorth** [comment]
> Out of scope question: sometimes the "...complaints could not be mapped" is covering the tooltip's header, so the complaint number, status and sometimes the line below it cannot be seen, and users have to move the map around to find perfect spot to view the tooltip. Do we want to address this UIUX issue? 🤔

I talked about this with the design team and we have a solution in place - however it is won't be part of this ticket.

**Comment by jeznorth** [comment]
> @jeznorth I view this in Google using Mac, and it has this weird icon "?". Also this line has black colour, which is different from the greyish in the design 🤔 Screen Shot 2024-07-10 at 10 01 24 AM

I'll address the missing character, however the horizontal rule uses the 'gray' variables from the pattern library, and it's verified with the design team.

**Review by Scarlett-Truong — APPROVED** [review]

**Review by Scarlett-Truong — APPROVED** [review]

**Pull request merged**
