### PR TITLE
feat: CE-1028 - Add Close Button to Desktop Filters

### PR DESCRIPTION
**Pull request by jeznorth**
# Description

Adding a close button to the filter drawer for desktop.

Fixes #CE-1028

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Manually Tested
- [ ] Test B

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Further comments

---

Thanks for the PR!

Deployments, as required, will be available below:
- [Frontend](https://nr-compliance-enforcement-615-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-615-frontend.apps.silver.devops.gov.bc.ca/api)

Please create PRs in draft mode.  Mark as ready to enable:
- [Analysis Workflow](https://github.com/bcgov/nr-compliance-enforcement/actions/workflows/analysis.yml)

After merge, new images are deployed in:
- [Merge Workflow](https://github.com/bcgov/nr-compliance-enforcement/actions/workflows/merge.yml)

### CODE REVIEW

**Review by Scarlett-Truong — CHANGES_REQUESTED** [review]
@jeznorth functionality working as expected. However, the styling is not consistent with the mobile one: 
In mobile, the default colour is grey and its hover state is a bolder grey. 
In desktop, the colour is dark blue and its hover state has a blue background
Screenshot 2024-09-09 at 11 53 17 AM
Screenshot 2024-09-09 at 11 54 05 AM

**Comment by jeznorth** [comment]
Hey Scarlett,

Not too worried about the mobile styling given this view is only available in small viewports which for the most part do not support 'hover' events'. The button styling is a global pattern previously established that I am leveraging.

**Comment by Scarlett-Truong** [comment]
@jeznorth urrr it's also different with the existing style of the close button in the modal...
I mean the mobile and modal are in sync in style rn. Only this new close button looks different. 
Screenshot 2024-09-09 at 11 52 11 AM

**Comment by jeznorth** [comment]
> @jeznorth urrr it's also different with the existing style of the close button in the modal... I mean the mobile and modal are in sync in style rn. Only this new close button looks different. Screenshot 2024-09-09 at 11 52 11 AM

We're splitting hairs here. One could argue the out of the box 'close' buttons should be updated appropriately to support appropriate hover states. I'll create a custom style to accommodate this then for this one-off.

**Review by Scarlett-Truong — APPROVED** [review]

**Pull request merged**
