### PR TITLE
feat: add IaC sysdig alerts

### PR DESCRIPTION
**Pull request by jon-funk**
# Description

Adds a suite of sysdig alerts, version controlled via terraform and managed state via NRS object storage

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Tested deployment, and pipeline
- [x] verified emails recieved from alerts

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Further comments

---

Thanks for the PR!

Deployments, as required, will be available below:
- [Frontend](https://nr-compliance-enforcement-725-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-725-frontend.apps.silver.devops.gov.bc.ca/api)

Please create PRs in draft mode.  Mark as ready to enable:
- [Analysis Workflow](https://github.com/bcgov/nr-compliance-enforcement/actions/workflows/analysis.yml)

After merge, new images are deployed in:
- [Merge Workflow](https://github.com/bcgov/nr-compliance-enforcement/actions/workflows/merge.yml)

---

Thanks for the PR!

Deployments, as required, will be available below:
- [Frontend](https://nr-compliance-enforcement-725-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-725-frontend.apps.silver.devops.gov.bc.ca/api)

Please create PRs in draft mode.  Mark as ready to enable:
- [Analysis Workflow](https://github.com/bcgov/nr-compliance-enforcement/actions/workflows/analysis.yml)

After merge, new images are deployed in:
- [Merge Workflow](https://github.com/bcgov/nr-compliance-enforcement/actions/workflows/merge.yml)

### CODE REVIEW

**Comment by mishraomp** [comment]
nice work @jon-funk , would love to port it back to qsos ;)
cc @DerekRoberts

**Comment by jon-funk** [comment]
Team wiki entry for updating channels/alerts incoming shortly

**Comment by jon-funk** [comment]
Note: the if conditional in the github action will be uncommented once approved

**Comment by jon-funk** [comment]
wiki entry: https://github.com/bcgov/nr-compliance-enforcement/wiki/SysDig#updating--adding-alerts

**Review by afwilcox — APPROVED** [review]

**Pull request merged**
