### PR TITLE
feat:Caddy Updates

### PR DESCRIPTION
**Pull request by mishraomp**
1. Serve static config without volume mounts
2. Align Caddyfile to proper zoning with ports.
3. Reduce log noise by using port 3001 to health checks.

---

Thanks for the PR!

Any successful deployments (not always required) will be available below.
[Backend](https://nr-compliance-enforcement-72-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-72-frontend.apps.silver.devops.gov.bc.ca/) available

Once merged, code will be promoted and handed off to following workflow run.
[Main Merge Workflow](https://github.com/bcgov/nr-compliance-enforcement/actions/workflows/merge-main.yml)

### CODE REVIEW

**Review by afwilcox — COMMENTED** [review]
@mishraomp 

I think the Healthcheck port in the Dockerfile is incorrect.  (30001 vs 3001)

**Comment by mishraomp** [comment]
> @mishraomp
> 
> I think the Healthcheck port in the Dockerfile is incorrect. (30001 vs 3001)



> @mishraomp
> 
> I think the Healthcheck port in the Dockerfile is incorrect. (30001 vs 3001)

good catch, will push the change

**Comment by mishraomp** [comment]
@afwilcox @barrfalk @marqueone-ps @cnesmithsalus  since I dont have access to the openshift environment, I am not able to figure out why the cypress tests are failing. I am happy to have a chat on this one when you guys have time.

**Comment by afwilcox** [comment]
@mishraomp  - Don't worry about the cypress tests, they are failing because the data required isn't in the environment.   We have a pending task to incorporate our seed data into the non-production environments as part of the pipeline process.

**Review by barrfalk — APPROVED** [review]

**Pull request merged**
