### PR TITLE
feat/CE-514: add banner to map view

### PR DESCRIPTION
**Pull request by marqueone-ps**
# Description
Update to the map component to allow the system to display message when no search results are found

Story # CE-514

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Show banner when no search results found
- [x] Show banner when no mappable results found

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Further comments

---

Thanks for the PR!

Any successful deployments (not always required) will be available below.
[Backend](https://nr-compliance-enforcement-308-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-308-frontend.apps.silver.devops.gov.bc.ca/) available

Once merged, code will be promoted and handed off to following workflow run.
[Main Merge Workflow](https://github.com/bcgov/nr-compliance-enforcement/actions/workflows/merge-main.yml)

### CODE REVIEW

**Comment by afwilcox** [comment]
@marqueone-ps - there is one scenario that doesn't work correctly, and one scenario that I'm not sure about.

Scenario 1: One Complaint in Filter View, Complaint has coordinates.   (Example I've setup in this PR: South Island, Caribou, Open)

Expected Behavior: Banner does not appear

Actual Behavior: Banner appears

Scenario 2: One Complaint in Filter View, Complaint has no coordinates.   (Example I've setup in this PR: South Island, Bison, Open)

Expected Behavior: I feel like it should say 1 complaint could not be mapped, but I'm not confident.   Will ask in standup today.

Actual Behavior: Banner appears

Also there is a minor code smell about a commented out line in the Cypress test... if you could just nuke that along with this fix that would be great.

**Comment by marqueone-ps** [comment]
@afwilcox, update made this should satisfy everything now.

**Comment by marqueone-ps** [comment]
case 1: unmapped items
status: open
specie: bison
zone: south island 
image

case2: all complaints mapped
status: open
specie: caribou
zone: south island 
image

case 3: no complaints 
status: open
specie: caribou
zone: south island 
community: cobble hill
status: open
specie: caribou
zone: south island 
image

This should cover everything now

**Comment by afwilcox** [comment]
Sorry @marqueone-ps the first case is still not working correctly for me.   

image

**Review by afwilcox — APPROVED** [review]

**Pull request merged**
